Stbe 10 teacher registration ep
mohammed-sharraf-sazim/SuperTeacher-BE pull request #15
Opened 2024-08-27 14:44 UTC by mohammed-sharraf-sazim

## Description of Change
- Addition of unique code generation endpoint
- Addition of teacher registration endpoint
## Associated Ticket Link(s)
- https://trello.com/c/8NczZEw8/10-subtask-22-implement-backend-api-for-teacher-registration
- https://trello.com/c/J4S8uUI1/11-subtask-23-implement-error-handling-for-unique-code-verification
## Developer Note(s):
- Github Actions have been removed so 5 changes for that reason
- Made some changes in the teacher entity which lead to a new migration file
- The Teacher module is only created so that I can link the teachers.repository.ts with my teacher entity to follow the nestjs template.
- Main files to look upon are the codes module for generating a unique code for teacher registration and usersService.ts for registering a teacher

2024-08-28 05:42 UTC, nur-zaman-sazim requested changes

2024-08-28 05:42 UTC, nur-zaman-sazim commented on src/codes/codes.repository.ts
> +    uniqueCode.email = email;
Please move this to service layer

2024-08-28 05:42 UTC, nur-zaman-sazim commented on src/codes/codes.service.ts
> +    const newGenereatedCode = await this.uniqueCodeRepository.generateUniqueCode(email);
nit: `newGeneratedCode` fix the typo

2024-08-28 05:42 UTC, nur-zaman-sazim commented on src/codes/codes.service.ts
> +  }
```suggestion
async validateUniqueCode(code: string, email: string): Promise<UniqueCode | null> {
    const uniqueCode = await this.uniqueCodeRepository.findByEmail(email);

    if (!uniqueCode) {
      throw new BadRequestException(`No code found for the provided email.`);
    }

    if (uniqueCode.isUsed) {
      await this.updateAttempts(uniqueCode);
      throw new BadRequestException(`Unique code has already been used.`);
    }

    if (uniqueCode.code !== code) {
      if (uniqueCode.attempts <= 0) {
        await this.entityManager.removeAndFlush(uniqueCode);
        throw new BadRequestException(`Attempts exceeded. Request a new code.`);
      }
      uniqueCode.attempts -= 1;
      await this.updateAttempts(uniqueCode);
      throw new BadRequestException(`Incorrect code. ${uniqueCode.attempts} attempts remaining.`);
    }

    return uniqueCode;
  }

  private async updateAttempts(uniqueCode: UniqueCode) {
    await this.entityManager.persistAndFlush(uniqueCode);
  }

```

2024-08-28 05:42 UTC, nur-zaman-sazim commented on src/users/users.controller.ts
> +    // console.log(newTeacher);
please remove comments

2024-08-30 15:50 UTC, mohammed-sharraf-sazim commented on src/codes/codes.repository.ts
> +    uniqueCode.email = email;
Moved it to service layer

2024-08-30 15:50 UTC, mohammed-sharraf-sazim commented on src/codes/codes.service.ts
> +  }
Suggestion added

2024-08-30 15:50 UTC, mohammed-sharraf-sazim commented on src/users/users.controller.ts
> +    // console.log(newTeacher);
Removed

2024-08-31 04:23 UTC, mahir-mohsin-sazim approved these changes

2024-08-31 07:02 UTC, merged