STBE-41: add db config, migrations and entities
mohammed-sharraf-sazim/SuperTeacher-BE pull request #7
Opened 2024-08-19 15:24 UTC by mohammed-sharraf-sazim

## Description of Change

- Add users, teachers and students entities
- Add the required migration file
- Removed not required files

## Associated Ticket Link(s)

- https://trello.com/c/DJ5QcoM2/41-db-config

## Developers Note
- testing commented for pre-commit for .husky

2024-08-22 11:20 UTC, mahir-mohsin-sazim requested changes
Please remove github actions and dependabot, otherwise you will see a "cross" beside your every PR

2024-08-24 05:54 UTC, mohammed-sharraf-sazim commented
> Please remove github actions and dependabot, otherwise you will see a "cross" beside your every PR

Github actions and dependabot removed

2024-08-25 10:39 UTC, nur-zaman-sazim approved these changes

2024-08-25 10:39 UTC, nur-zaman-sazim commented on src/common/entities/students.entity.ts
> +  semesterOrYear?: string;
[NIT] can we separate semesterOrYear in to two Property ?

2024-08-26 08:20 UTC, mahir-mohsin-sazim approved these changes

2024-08-27 05:45 UTC, merged