Stbe 6 user registration
mohammed-sharraf-sazim/SuperTeacher-BE pull request #8
Opened 2024-08-22 05:59 UTC by mohammed-sharraf-sazim

## Description of Change:
- Removal of unnecessary files
- Modification of necessary files
- Addition of Student Registration API endpoint

## Associated Ticket Link(s):
- https://trello.com/c/P4O2Yg46/8-subtask-14-automatic-login-after-registration

## Developer Note(s): 
- In this commit, [chore(STBE-6): deletion of unnecessary files and modification of nece…](https://github.com/mohammed-sharraf-sazim/SuperTeacher-BE/commit/c5327388a76a3ea2d817c9c544aac7f782962f5b), unnecessary files have been removed and some modifications have been done in or order to create the student registration api. So this commit does not require any review and can be ignored.
- In this commit, [feat(STBE-6): implementation of student-user registration](https://github.com/mohammed-sharraf-sazim/SuperTeacher-BE/commit/8528df459f2b6eb6d36949bcaf4e6b6776b6efc8), the actual student api endpoint has been created which requires a review.

2024-08-25 11:29 UTC, nur-zaman-sazim reviewed
Do we need [src/students/](https://github.com/mohammed-sharraf-sazim/SuperTeacher-BE/pull/8/files#diff-4e49b8b83f7f9f96003467f9eaf033e5d9e209376b9d024026355ff70f04d3f5) for this PR ?

2024-08-28 05:42 UTC, nur-zaman-sazim approved these changes

2024-08-28 06:01 UTC, mahir-mohsin-sazim requested changes
Please fix the cross sign beside your PRs asap

2024-08-28 13:30 UTC, mohammed-sharraf-sazim commented
> Please fix the cross sign beside your PRs asap
The cross sign has been removed

2024-08-28 13:31 UTC, nur-zaman-sazim approved these changes

2024-08-28 14:36 UTC, mahir-mohsin-sazim approved these changes

2024-08-31 06:45 UTC, merged