STBE-8: Student login endpoint
mohammed-sharraf-sazim/SuperTeacher-BE pull request #9
Opened 2024-08-24 05:49 UTC by mohammed-sharraf-sazim

## Description of Change
- Modification the the data type of phone number for a student from integer to string
- Addition of token while registering a student for automatic login functionality

## Associated Ticket Link(s)
- https://trello.com/c/P4O2Yg46/8-subtask-14-automatic-login-after-registration
- https://trello.com/c/uaavqU8a/6-subtask-12-implement-backend-api-for-student-registration

## Developer Note(s):
- login for both student or teacher is already implemented with the help of the template used for this project

2024-08-25 11:33 UTC, nur-zaman-sazim requested changes

2024-08-25 11:33 UTC, nur-zaman-sazim commented on src/users/users.service.ts
> +    const accessToken = await this.jwtService.signAsync(payload);
We are using it often. Can we make it a function ?

2024-08-28 14:39 UTC, mahir-mohsin-sazim approved these changes

2024-08-28 15:11 UTC, nur-zaman-sazim approved these changes

2024-08-31 07:01 UTC, merged